---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include_tasks: remove-defaults.yml

- include_tasks: create-directories.yml

- include_tasks: remove-unmanaged.yml

- include_tasks: configuration.yml
