---
- name: Include OS-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: remove-defaults.yml

- include: create-directories.yml

- include: remove-unmanaged.yml

- include: configuration.yml
