---
- name: Disable the default site
  file:
    path: '{{ nginx_conf_dir }}/sites-enabled/default'
    state: absent
  notify:
  - Reload nginx

- name: Search for default configuration files that can be removed
  shell: >
    find {{nginx_conf_dir}} -maxdepth 1
    -name '*.default' -o
    -name 'fastcgi.conf' -o
    -name 'default.d' -o
    -name 'naxsi*' -o
    -name 'proxy_params'
  register: default_files
  changed_when: False
  tags: skip_ansible_lint

- name: Remove previous found default configuration files
  file:
    path: '{{ item }}'
    state: absent
  with_items: '{{ default_files.stdout_lines }}'
  notify:
  - Reload nginx
