---
- hosts: all

  roles:
    - { role: jgeusebroek.epel, when: ansible_os_family == 'RedHat' }

  tasks:
    - name: Ensure GnuPG is installed (Debian)
      package:
        name: gnupg
        state: present
      changed_when: false
      when: ansible_os_family == 'Debian'
